name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        run: |
          echo "## Release Notes for ${{ github.ref }}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          git log "${{ github.ref }}..HEAD" --pretty=format:'- %s' >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## Contributors" >> RELEASE_NOTES.md
          git log "${{ github.ref }}..HEAD" --pretty=format:'* %an' | sort | uniq >> RELEASE_NOTES.md

      - name: Commit Release Notes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add RELEASE_NOTES.md
          git commit -m "Update release notes for ${{ github.ref }}"
          git push
