apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: default  # Adjust to your namespace
data:
  index.js: |
    const express = require('express');
    const app = express();
    
    app.get('/', (req, res) => {
      res.send('Hello, OpenTelemetry!');
    });
    
    const port = 3000;
    app.listen(port, () => {
      console.log(`Server is running on http://localhost:${port}`);
    });
