apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-rolebinding
  namespace: otel
subjects:
- kind: ServiceAccount
  name: default # replace with the actual service account name if different
  namespace: otel
roleRef:
  kind: Role
  name: otel-role
  apiGroup: rbac.authorization.k8s.io
