apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: otel
  name: otel-role
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
