apiVersion: v1
kind: PersistentVolume
metadata:
  name: reportportal-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/reportportal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reportportal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
